services:
  rabbitmq:
    image: rabbitmq:management
    container_name: dev-omcs-rabbitmq
    volumes:
      - rabbitmq-etc:/etc/rabbitmq/
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq/
    ports:
      - ${AMQP_PORT}:5672
      - ${AMQP_IHM_PORT}:15672

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: dev-omcs-opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${ES_PASSWORD}
      # - AWS_EC2_METADATA_DISABLED=true
      - DISABLE_SECURITY_PLUGIN=true # Disables Security plugin
      - DISABLE_INSTALL_DEMO_CONFIG=true # Disables Security plugin
      # Add S3 client settings
      # - s3.client.default.region=us-east-1
      # - s3.client.default.endpoint=minio:9000
      # - s3.client.default.protocol=http
      # - s3.client.default.access_key=3w4u7xTZzOGelxQUMI4Uc0miMU4j5WxNMFhHM2h6
      # - s3.client.default.secret_key=jaEgV8P3n5OlThJc0ppS
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      # - opensearch-data:/usr/share/opensearch/data
      - opensearch-data:/usr/share/opensearch/data
      # - opensearch-config:/usr/share/opensearch/config
      # - ./opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - ${ES_PORT}:9200
    # Bypass cert different than remote access
    # extra_hosts: 
    #   - "cert_HOST:real_HOST"

  grafana:
    image: grafana/grafana:11.4.0
    container_name: dev-omcs-grafana
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_INSTALL_PLUGINS: "marcusolsson-gantt-panel,https://github.com/yesoreyeram/grafana-infinity-datasource/releases/download/v2.4.0/yesoreyeram-infinity-datasource-2.4.0.zip;yesoreyeram-infinity-datasource"
      ES_URL: ${ES_INTERNAL_URL}
      ES_USERNAME: ${ES_USERNAME}
      ES_PASSWORD: ${ES_PASSWORD}
    ports:
      - ${GRF_PORT}:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      # MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  rabbitmq-etc:
  rabbitmq-data:
  rabbitmq-logs:
  opensearch-data:
  # opensearch-logs:
  minio_data:
