apiVersion: 1
datasources:
- name: cds-interface-status-monitoring-start
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: cds-interface-status-monitoring
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: status_time_start
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
