apiVersion: 1
datasources:
- name: cds-acquisition-pass-status
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: cds-acquisition-pass-status
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: planned_data_start
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
