apiVersion: 1
datasources:
- name: cds-cams-tickets-updates
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: cds-cams-tickets
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: updated
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
