apiVersion: 1
datasources:
- name: cds-metrics-product
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: '[cds-metrics-product-]YYYY'
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    interval: Yearly
    timeField: timestamp
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
