apiVersion: 1
datasources:
- name: cds-publication-monitoring
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: cds-publication
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: updateTime
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
