apiVersion: 1
datasources:
- name: cds-sat-unavailability
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: cds-sat-unavailability
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: start_time
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
