apiVersion: 1
datasources:
- name: cds-hktm-acquisition-completeness
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: cds-hktm-acquisition-completeness
  basicAuth: true
  isDefault: false
  jsonData:
    includeFrozen: false
    index: cds-hktm-acquisition-completeness
    timeField: execution_time
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
