apiVersion: 1
datasources:
- name: cds-product-ddip-publication
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: cds-product
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: ddip_publication_date
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
