apiVersion: 1
datasources:
- name: cds-lta-download-quota-conf
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: ''
  basicAuth: true
  isDefault: false
  jsonData:
    includeFrozen: false
    index: cds-lta-download-quota-conf
    oauthPassThru: false
    sigV4Auth: false
    timeField: timestamp
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
