apiVersion: 1
datasources:
- name: cds-ddp-data-available
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: cds-ddp-data-available
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: time_created
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
