apiVersion: 1
datasources:
- name: cds-hktm-production-completeness
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: ''
  basicAuth: true
  isDefault: false
  jsonData:
    includeFrozen: false
    index: cds-hktm-production-completeness
    oauthPassThru: false
    sigV4Auth: false
    timeField: effective_downlink_start
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
