apiVersion: 1
datasources:
- name: cds-product-sensing-alias
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: ''
  basicAuth: true
  isDefault: false
  jsonData:
    includeFrozen: false
    index: cds-product
    oauthPassThru: false
    sigV4Auth: false
    timeField: sensing_start_date
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
