apiVersion: 1
datasources:
- name: Infinity
  type: yesoreyeram-infinity-datasource
  access: proxy
  url: ${ES_URL}
  database: ''
  basicAuth: true
  isDefault: false
  jsonData:
    allowedHosts:
    - ${ES_URL}
    auth_method: basicAuth
    global_queries: []
    oauthPassThru: false
    secureQueryName1: ''
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
