apiVersion: 1
datasources:
- name: maas-collector-journal
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: maas-collector-journal
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: last_collect_date
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
