apiVersion: 1
datasources:
- name: raw-data-aps-edrs-product
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: raw-data-aps-edrs-product
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    includeFrozen: false
    timeField: ingestionTime
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
