apiVersion: 1
datasources:
- name: raw-data-mp-all-product-sensing
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: raw-data-mp-all-product
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: effective_downlink_start
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
