apiVersion: 1
datasources:
- name: raw-data-sat-unavailability-product
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: raw-data-sat-unavailability
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: ingestionTime
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
