apiVersion: 1
datasources:
- name: raw-data-prip-product
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: '[raw-data-prip-product-]YYYY-MM'
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    interval: Monthly
    timeField: ingestionTime
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
