apiVersion: 1
datasources:
- name: raw-data-das-product
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: ''
  basicAuth: true
  isDefault: false
  jsonData:
    includeFrozen: false
    index: '[raw-data-das-product-]YYYY'
    interval: Yearly
    oauthPassThru: false
    sigV4Auth: false
    timeField: ingestionTime
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
