apiVersion: 1
datasources:
- name: raw-data-grafana-usage
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: ''
  basicAuth: true
  isDefault: false
  jsonData:
    includeFrozen: false
    index: raw-data-grafana-usage
    oauthPassThru: false
    sigV4Auth: false
    timeField: access_date
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
