apiVersion: 1
datasources:
- name: raw-data-dd-product
  type: elasticsearch
  access: proxy
  url: ${ES_URL}
  database: '[raw-data-dd-product-]YYYY'
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    interval: Yearly
    timeField: ingestionTime
    tlsSkipVerify: true
  editable: true
  basicAuthUser: ${ES_USERNAME}
  secureJsonData:
    basicAuthPassword: ${ES_PASSWORD}
