{{ if and .Values.skedler.enabled .Values.skedler.ingress.enabled }}
{{- $name := include "skedler.name" . -}}
{{- $fullName := include "skedler.fullname" . -}}
{{- $servicePort := .Values.skedler.service.port -}}
{{- $ingressPath := .Values.skedler.ingress.path -}}
{{- $ingressPathType := .Values.skedler.ingress.pathType -}}
{{- $extraPaths := .Values.skedler.ingress.extraPaths -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "skedler.labels" . | nindent 4 }}
{{- if .Values.skedler.ingress.labels }}
{{ toYaml .Values.skedler.ingress.labels | indent 4 }}
{{- end }}
  {{- if .Values.skedler.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.skedler.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.skedler.ingress.ingressClassName }}
  ingressClassName: {{ .Values.skedler.ingress.ingressClassName }}
  {{- end -}}
{{- if .Values.skedler.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.skedler.ingress.tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if .Values.skedler.ingress.hosts  }}
  {{- range .Values.skedler.ingress.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
{{- if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            pathType: {{ $ingressPathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
            {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
            pathType: {{ $ingressPathType }}
  {{- end -}}
{{- end }}
