apiVersion: 1
datasources:
- name: cds-cams-tickets-updates
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: cds-cams-tickets
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: updated
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
