apiVersion: 1
datasources:
- name: cds-metrics-product
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: '[cds-metrics-product-]YYYY'
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    interval: Yearly
    timeField: timestamp
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
