apiVersion: 1
datasources:
- name: cds-hktm-acquisition-completeness
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: cds-hktm-acquisition-completeness
  basicAuth: true
  isDefault: false
  jsonData:
    includeFrozen: false
    index: cds-hktm-acquisition-completeness
    timeField: execution_time
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
