apiVersion: 1
datasources:
- name: cds-interface-status-monitoring-stop
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: cds-interface-status-monitoring
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: status_time_stop
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
