apiVersion: 1
datasources:
- name: cds-publication
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: '[cds-publication-]YYYY-MM'
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    interval: Monthly
    timeField: sensing_start_date
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
