apiVersion: 1
datasources:
- name: cds-product-ddip-publication
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: cds-product
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: ddip_publication_date
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
