apiVersion: 1
datasources:
- name: cds-s3-completeness-monitoring
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: cds-s3-completeness
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: updateTime
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
