apiVersion: 1
datasources:
- name: cds-databudget-conf
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: ''
  basicAuth: true
  isDefault: false
  jsonData:
    includeFrozen: false
    index: cds-databudget-conf
    oauthPassThru: false
    sigV4Auth: false
    timeField: ingestionTime
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
