apiVersion: 1
datasources:
- name: external-interfaces-counting
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: external-interfaces-counting
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    includeFrozen: false
    timeField: check_date
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
