apiVersion: 1
datasources:
- name: maas-collector-journal
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: maas-collector-journal
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: last_collect_date
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
