apiVersion: 1
datasources:
- name: raw-data-dd-product
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: '[raw-data-dd-product-]YYYY'
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    interval: Yearly
    timeField: ingestionTime
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
