apiVersion: 1
datasources:
- name: raw-data-cams-tickets
  type: elasticsearch
  access: proxy
  url: 'https://omcs-es-node:9200'
  database: raw-data-cams-tickets
  basicAuth: true
  isDefault: false
  jsonData:
    esVersion: 7.10.0
    timeField: ingestionTime
    tlsSkipVerify: true
  editable: true
  basicAuthUser: 'admin'
  secureJsonData:
    basicAuthPassword: 'admin'
