{
 "title": "S3 Production Completeness (Produced vs Planned)",
 "tags": [ "Completeness" ],
 "time": { "from": "now-1d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S3" },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: $mission\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\": \"terms\", \"field\": \"timeliness\",\"query\":\"mission: $mission AND satellite_unit : $satellite\"}"
   },
   {
    "name": "product_level",
    "label": "Level",
    "query": "{\"find\": \"terms\", \"field\": \"product_level\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\": \"terms\", \"field\": \"product_type\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness AND product_level:$product_level\"}"
   },
   {
    "name": "datatake_id",
    "label": "Datatake Id",
    "query": "{\"find\": \"terms\", \"field\": \"datatake_id\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness\"}"
   },
   { "name": "Filters", "label": "Ad-Hoc filter" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features Completeness computation on S3 mission.\r\n\r\nComparison is done using the following:\r\n - PRIP: Produced products.\r\n\r\nDatatake ID are built from:\r\n - Satellite number;\r\n - Cycle number;\r\n - Relative orbit number.\r\n\r\nWhen one PRIP product is published, every expected product related to this datatake is created.\r\n\r\nMissing products are displayed in purple.\r\n\r\nTips:\r\n - Annotations are available on time series;\r\n - Satellite to consider can be selected in the upper bar.\r\n\r\nNote: \r\n - SRAL L2, VG1 and V10 products are not included in the completeness computation since these products are not systematically produced at each orbit (production is not predictable).\r\n\n\nThe information displayed was originally taken from Product at PRIP  \n\nTime reference for this dashboard is : observation_time_start\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     }
    }
   ]
  },
  { "title": "Overall Completeness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Overall Completeness",
   "type": "gauge",
   "description": "Overall Completeness over the period",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "expected", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : $product_level",
     "timeField": "observation_time_start"
    },
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value_adjusted", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : $product_level",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "per Timeliness",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timeliness",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "expected", "id": "1", "type": "sum" },
      {
       "field": "value_adjusted",
       "hide": false,
       "id": "3",
       "type": "sum"
      }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : $product_level",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "per Product Level",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "product_level",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "expected", "id": "1", "type": "sum" },
      {
       "field": "value_adjusted",
       "hide": false,
       "id": "3",
       "type": "sum"
      }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : $product_level",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Average Completeness over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "observation_time_start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "value_adjusted", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : $product_level",
     "timeField": "observation_time_start"
    },
    {
     "bucketAggs": [
      {
       "field": "observation_time_start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "expected", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit : $satellite AND timeliness : $timeliness AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : $product_level",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake completeness per timeliness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Datatake completeness timeline ${timeliness}",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "repeat": "timeliness",
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : $product_level",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake Product list",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "datatake_id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "expected",
       "hide": false,
       "id": "1",
       "type": "sum"
      },
      { "field": "value_adjusted", "id": "3", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness  AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : $product_level",
     "timeField": "observation_time_start"
    },
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness  AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : $product_level",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "L0 Datatake list",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 69 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "datatake_id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
       "type": "terms"
      },
      {
       "field": "satellite_unit",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "expected",
       "hide": false,
       "id": "1",
       "type": "sum"
      },
      { "field": "value_adjusted", "id": "3", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness  AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : L0_",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "L1 Datatake list",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 69 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "datatake_id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
       "type": "terms"
      },
      {
       "field": "satellite_unit",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "expected",
       "hide": false,
       "id": "1",
       "type": "sum"
      },
      { "field": "value_adjusted", "id": "3", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness  AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : L1_",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "L2 Datatake list",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "datatake_id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
       "type": "terms"
      },
      {
       "field": "satellite_unit",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "expected",
       "hide": false,
       "id": "1",
       "type": "sum"
      },
      { "field": "value_adjusted", "id": "3", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness  AND datatake_id : $datatake_id AND product_type : $product_type AND product_level : L2_",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "HKTM & GPS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "HKTM & GPS Products Timeline",
     "type": "marcusolsson-gantt-panel",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:$mission AND satellite_unit: $satellite AND ( product_type: *HK* OR product_type:PRD_GP__)",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "HKTM & GPS Products list",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:$mission AND satellite_unit: $satellite AND (product_type: *HK* OR product_type: GN*)",
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  }
 ]
}