name: Run Docker build for python

on:
  push:
    tags:
      - '*'

jobs:
  docker-build:
    runs-on: ubuntu-22.04

    needs: build-wheel

    strategy:
      matrix:
        module: [maas-model, maas-engine, maas-collector, maas-cds]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download specific artifact
      uses: actions/download-artifact@v4
      with:
        name: wheel-wheel-${{ matrix.module }}
        path: ./modules/build/

    - name: Build Docker images
      run: |
        TAG_NAME=${{ github.ref_name }}
        docker build --no-cache -t "maas-cds:${TAG_NAME}" -f ./modules/Dockerfile.maas-cds ./modules
        docker build --no-cache -t "maas-collector:${TAG_NAME}" -f ./modules/Dockerfile.maas-collector ./modules
