name: Run Build Python

on:
  push:
    tags:
      - '*'

jobs:
  python-build:
    runs-on: ubuntu-22.04
    needs: test
    strategy:
      matrix:
        module: [maas-model, maas-engine, maas-collector, maas-cds]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.11'
        architecture: x64

    - name: Install tox
      run: pip install tox

    - name: Build wheels
      run: |
        tox -c ./modules/${{ matrix.module }}/tox.ini -e build
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.module }}
        path: ./modules/${{ matrix.module }}/dist/
