name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        module: [maas-model, maas-engine, maas-collector, maas-cds]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.11'

    - name: Init venv
      run: |
        python -m venv venv

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -e ./modules/maas-model
        pip install -e ./modules/maas-engine
        pip install -e ./modules/maas-collector
        pip install -e ./modules/maas-cds

    - name: Install test dependencies
      run: |
        source venv/bin/activate
        pip install pytest
        pip install pytest-cov
        pip install wheel
    - name: Run tests
      run: |
        source venv/bin/activate
        pytest ./modules/${{ matrix.module }}/tests --junitxml=reports/${{ matrix.module }}-results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.module }}
        path: reports/${{ matrix.module }}-results.xml
